# MATH 210 Introduction to Mathematical Computing

**April 7, 2025**

In [2]:
import numpy as np
import scipy.linalg as la

## Power Method

In [3]:
A = np.array([[1.,2.],[2.,1.]])
A

array([[1., 2.],
       [2., 1.]])

In [4]:
evals,evecs = la.eig(A)

In [5]:
evals.real

array([ 3., -1.])

In [6]:
xk = np.array([[1.],[0.]])
for k in range(15):
    y = A@xk
    #xk = y/la.norm(y)
    xk = y/np.max(np.abs(y))

print(xk)

[[0.99999986]
 [1.        ]]


In [10]:
xk.T@A@xk/(xk.T@xk)

array([[3.]])

In [11]:
A = np.array([[1.,1.,0.],[1.,1.,1.],[0.,1.,1.,]])
xk = np.array([[1.],[0.],[0.]])

for k in range(10):
    y = A@xk
    xk = y/np.max(np.abs(y))

print(xk)

[[0.70731707]
 [1.        ]
 [0.70689655]]


In [12]:
print(xk.T@A@xk/(xk.T@xk))

[[2.4142135]]
