# MATH 210 Introduction to Mathematical Computing

**March 7, 2025**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Simpson's Rule

$$
S_N(f) = \frac{\Delta x}{3} \sum_{m=1}^{N/2} ( f(x_{2m-2}) + 4 f(x_{2m-1}) + f(x_{2m}))
$$

In [2]:
f = lambda x: 1/np.log(x)
a = np.e
b = np.e**2
N = 10
dx = (b - a)/N
x = np.linspace(a,b,N+1)
y = f(x)

In [3]:
y

array([1.        , 0.86313667, 0.77196559, 0.70634677, 0.65653969,
       0.61724032, 0.58530427, 0.55874411, 0.53623911, 0.51687556,
       0.5       ])

Note that the terms $f(x_{2m-2})$ in the sum correspond to all the even indices from 0 up to $N-2$. We can use fancy indexing to select those values. Bascially we just enter the list of indices `[0,2,4,...,N-2]` using `range(0,N,2)`.

In [6]:
# Values at even indices from 0 up to N-2
y[range(0,N,2)]

array([1.        , 0.77196559, 0.65653969, 0.58530427, 0.53623911])

The terms $f(x_{2m-1})$ in the sum correspond to all the odd indices from 1 up to $N-1$.

In [7]:
# Values at odd indices up to N-1
y[range(1,N,2)]

array([0.86313667, 0.70634677, 0.61724032, 0.55874411, 0.51687556])

The terms $f(x_{2m})$ in the sum correspond to all the even indices from 2 up to $N$.

In [8]:
# Values at even indices from 2 up to N
y[range(2,N+1,2)]

array([0.77196559, 0.65653969, 0.58530427, 0.53623911, 0.5       ])

In [9]:
SN = dx/3*np.sum( y[range(0,N,2)] + 4*y[range(1,N,2)] + y[range(2,N+1,2)] )

In [10]:
SN

3.0592747891369285

In [11]:
def simps(f,a,b,N):
    dx = (b - a)/N
    x = np.linspace(a,b,N+1)
    y = f(x)
    SN = dx/3*np.sum( y[range(0,N,2)] + 4*y[range(1,N,2)] + y[range(2,N+1,2)] )
    return SN

Compute $K_4$:

In [12]:
K4 = (6*2**3 + 22*2**2 + 36*2 + 24)/np.exp(4)
K4

4.24922822218633

Compute $N$:

In [13]:
err = 0.01
N = ((b - a)**5*K4/err/180)**0.25
N

8.511291936241985

Therefore $N=10$ guarantees the error is less than 0.01:

In [14]:
simps(f,a,b,10)

3.0592747891369285

Let's use the function `scipy.integrate.simpson` to compute the value:

In [15]:
import scipy.integrate as spi

In [16]:
f = lambda x: 1/np.log(x)
a = np.e
b = np.e**2
N = 10
x = np.linspace(a,b,N+1)
y = f(x)

S = spi.simpson(y,x=x)
S

3.0592747891369294

There is also the function `quad` which uses quadrature to compute the approximation and estimate the error:

In [17]:
I,err = spi.quad(f,a,b)

In [18]:
I

3.059116539645953

In [19]:
err

1.1537798306539157e-11