# MATH 210 Introduction to Mathematical Computing

**April 4, 2025**

In [9]:
import numpy as np
import scipy.linalg as la

## Eigenvalues and Eigenvectors

In [10]:
A = np.array([[1.,2.],[2.,1.]])
A

array([[1., 2.],
       [2., 1.]])

The function `scipy.linalg.eig` returns a tuple. Unpack into variables `evals` and `evecs`.

In [14]:
evals,evecs = la.eig(A)

`evals` is a 1D NumPy array with complex entries. Use the `.real` attribute to get the real part if we know that eigenvalues are real.

In [15]:
evals.real

array([ 3., -1.])

The eigenvectors are the columns of `evecs`. They are normalized to be unit vectors.

In [13]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])